export const Employees = [
  {
    id: 1,
    name: "John Smith",
    phone: "02 9988 2211",
    department: 1,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 2,
    name: "Sue White",
    phone: "02 9988 2211",
    department: 2,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 3,
    name: "Bob O'Bits",
    phone: "02 9988 2211",
    department: 1,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 4,
    name: "Mary Blue",
    phone: "02 9988 2211",
    department: 2,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 5,
    name: "Mick Green",
    phone: "02 9988 2211",
    department: 3,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 6,
    name: "John Wick",
    phone: "02 9988 2211",
    department: 4,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 7,
    name: "Harry Potter",
    phone: "02 9988 2211",
    department: 1,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 8,
    name: "Elon Musk",
    phone: "02 9988 2211",
    department: 1,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 9,
    name: "Jennifer Lopez",
    phone: "02 9988 2211",
    department: 0,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
  {
    id: 10,
    name: "Lebron James",
    phone: "02 9988 2211",
    department: 1,
    addressStreet: "1 Code Lane",
    addressCity: "Jaraville",
    addressState: "NSW",
    addressZip: "0100",
    addressCountry: "Australia",
  },
];
